name: 'Contributor Map'
description: 'Generate an SVG map showing countries with the most contributions to a repository'
inputs:
  repository:
    description: 'Name of the repository for which generate the contributor map'
    required: true
  token:
    description: 'GitHub Token used to access the GitHub API'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: composite
  steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate map
      uses: docker://ghcr.io/tunaitis/contributor-map:dev
      with:
        repository: ${{ inputs.repository }}
        token: ${{ inputs.token }}

    - name: Commit the generated file back to the repository
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated Change
        repository: .

    - run: pwd
      shell: bash

    - run: ls -la
      shell: bash

  #args:
   # - ${{ inputs.who-to-greet }}